&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;xsl:stylesheet version=&quot;1.1&quot; xmlns=&quot;urn:hl7-org:v3&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:cda=&quot;urn:hl7-org:v3&quot; xmlns:trim=&quot;urn:tolven-org:trim:4.0&quot; exclude-result-prefixes=&quot;xs fn cda trim&quot;&gt;
	&lt;xsl:output method=&quot;xml&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot;/&gt;
	&lt;xsl:template match=&quot;/&quot;&gt;
		&lt;ClinicalDocument xmlns=&quot;urn:hl7-org:v3&quot;&gt;
			&lt;!-- &lt;xsl:attribute name=&quot;xsi:schemaLocation&quot; namespace=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;xsl:value-of select=&quot;'urn:hl7-org:v3 D:/workspace/Transcend_Trim_Mapping/mapping/CDA_XSD/cda/CDA.xsd'&quot;/&gt;&lt;/xsl:attribute&gt; --&gt;
			&lt;xsl:for-each select=&quot;trim:trim/trim:act&quot;&gt;
				&lt;xsl:call-template name=&quot;baseline_cdaHeader&quot;&gt;
					&lt;xsl:with-param name=&quot;trimAct&quot; select=&quot;current()&quot;/&gt;
				&lt;/xsl:call-template&gt;
			&lt;/xsl:for-each&gt;
			&lt;component&gt;
				&lt;structuredBody&gt;
					&lt;xsl:for-each select=&quot;trim:trim/trim:act/trim:relationship[@name='riskFactor']/trim:act/trim:relationship[@name='familyHistorys']&quot;&gt;
						&lt;!-- call family history section template --&gt;
						&lt;xsl:call-template name=&quot;familyHistory_section&quot;&gt;
							&lt;xsl:with-param name=&quot;fh_sec&quot; select=&quot;current()&quot;/&gt;
						&lt;/xsl:call-template&gt;
					&lt;/xsl:for-each&gt;
					&lt;xsl:for-each select=&quot;trim:trim/trim:act/trim:relationship[@name='vitalSigns']&quot;&gt;
						&lt;!-- call vital sign section template --&gt;
						&lt;xsl:call-template name=&quot;vitalSigns_section&quot;&gt;
							&lt;xsl:with-param name=&quot;vital_sec&quot; select=&quot;current()&quot;/&gt;
						&lt;/xsl:call-template&gt;
					&lt;/xsl:for-each&gt;
				&lt;/structuredBody&gt;
			&lt;/component&gt;
		&lt;/ClinicalDocument&gt;
	&lt;/xsl:template&gt;
	&lt;!-- ===================== --&gt;
	&lt;!-- cda header template --&gt;
	&lt;!-- ===================== --&gt;
	&lt;xsl:template name=&quot;baseline_cdaHeader&quot;&gt;
		&lt;xsl:param name=&quot;trimAct&quot;/&gt;
		&lt;realmCode xmlns=&quot;urn:hl7-org:v3&quot; code=&quot;US&quot;/&gt;
		&lt;typeId xmlns=&quot;urn:hl7-org:v3&quot; root=&quot;2.16.840.1.113883.1.3&quot; extension=&quot;POCD_HD000040&quot;/&gt;
		&lt;templateId xmlns=&quot;urn:hl7-org:v3&quot; root=&quot;2.16.840.1.113883.10.20.1&quot;/&gt;
		&lt;templateId xmlns=&quot;urn:hl7-org:v3&quot; root=&quot;2.16.840.1.113883.3.88.11.32.1&quot;/&gt;
		&lt;templateId xmlns=&quot;urn:hl7-org:v3&quot; root=&quot;1.3.6.1.4.1.19376.1.5.3.1.1.1&quot;/&gt;
		&lt;templateId xmlns=&quot;urn:hl7-org:v3&quot; root=&quot;2.16.840.1.113883.10.20.3&quot;/&gt;
		&lt;xsl:if test=&quot;\$trimAct/trim:id/trim:II&quot;&gt;
			&lt;xsl:call-template name=&quot;make_II&quot;&gt;
				&lt;xsl:with-param name=&quot;II_root&quot; select=&quot;\$trimAct/trim:id/trim:II/trim:root&quot;/&gt;
				&lt;xsl:with-param name=&quot;II_ext&quot; select=&quot;\$trimAct/trim:id/trim:II/trim:extension&quot;/&gt;
			&lt;/xsl:call-template&gt;
		&lt;/xsl:if&gt;
		&lt;xsl:if test=&quot;\$trimAct/trim:code/trim:CD&quot;&gt;
			&lt;xsl:call-template name=&quot;make_code_CD&quot;&gt;
				&lt;xsl:with-param name=&quot;CD_code&quot; select=&quot;\$trimAct/trim:code/trim:CD/trim:code&quot;/&gt;
				&lt;xsl:with-param name=&quot;CD_dispNm&quot; select=&quot;\$trimAct/trim:code/trim:CD/trim:displayName&quot;/&gt;
				&lt;xsl:with-param name=&quot;CD_codeSys&quot; select=&quot;\$trimAct/trim:code/trim:CD/trim:codeSystem&quot;/&gt;
				&lt;xsl:with-param name=&quot;CD_codeSysNm&quot; select=&quot;\$trimAct/trim:code/trim:CD/trim:codeSystemName&quot;/&gt;
			&lt;/xsl:call-template&gt;
		&lt;/xsl:if&gt;
		&lt;xsl:if test=&quot;\$trimAct/trim:title/trim:ST&quot;&gt;
			&lt;title xmlns=&quot;urn:hl7-org:v3&quot;&gt;
				&lt;xsl:value-of select=&quot;\$trimAct/trim:title/trim:ST&quot;/&gt;
			&lt;/title&gt;
		&lt;/xsl:if&gt;
		&lt;xsl:if test=&quot;\$trimAct/trim:effectiveTime/trim:TS/trim:value&quot;&gt;
			&lt;effectiveTime xmlns=&quot;urn:hl7-org:v3&quot;&gt;
				&lt;xsl:attribute name=&quot;value&quot;&gt;&lt;xsl:value-of select=&quot;\$trimAct/trim:effectiveTime/trim:TS/trim:value&quot;/&gt;&lt;/xsl:attribute&gt;
			&lt;/effectiveTime&gt;
		&lt;/xsl:if&gt;
		&lt;confidentialityCode xmlns=&quot;urn:hl7-org:v3&quot; code=&quot;N&quot;/&gt;
		&lt;xsl:for-each select=&quot;\$trimAct/trim:participation[@typeCode='SBJ'][trim:role/@classCode='PAT']&quot;&gt;
			&lt;recordTarget xmlns=&quot;urn:hl7-org:v3&quot;&gt;
				&lt;patientRole&gt;
					&lt;xsl:for-each select=&quot;trim:role/trim:id&quot;&gt;
						&lt;xsl:call-template name=&quot;make_II&quot;&gt;
							&lt;xsl:with-param name=&quot;II_root&quot; select=&quot;trim:II/trim:root&quot;/&gt;
							&lt;xsl:with-param name=&quot;II_ext&quot; select=&quot;trim:II/trim:extension&quot;/&gt;
						&lt;/xsl:call-template&gt;
					&lt;/xsl:for-each&gt;
					&lt;xsl:for-each select=&quot;trim:role/trim:player[@classCode='PSN']&quot;&gt;
						&lt;patient&gt;
							&lt;xsl:call-template name=&quot;make_name&quot;&gt;
								&lt;xsl:with-param name=&quot;trimNm&quot; select=&quot;trim:name&quot;/&gt;
							&lt;/xsl:call-template&gt;
						&lt;/patient&gt;
					&lt;/xsl:for-each&gt;
				&lt;/patientRole&gt;
			&lt;/recordTarget&gt;
		&lt;/xsl:for-each&gt;
		&lt;xsl:for-each select=&quot;\$trimAct/trim:participation[@typeCode='ENT'][trim:role/@classCode='ROL']&quot;&gt;
			&lt;author xmlns=&quot;urn:hl7-org:v3&quot;&gt;
				&lt;time nullFlavor=&quot;NI&quot;/&gt;
				&lt;assignedAuthor&gt;
					&lt;xsl:call-template name=&quot;make_II&quot;&gt;
						&lt;xsl:with-param name=&quot;II_root&quot; select=&quot;trim:role/trim:id/trim:II/trim:root&quot;/&gt;
						&lt;xsl:with-param name=&quot;II_ext&quot; select=&quot;trim:role/trim:id/trim:II/trim:extension&quot;/&gt;
					&lt;/xsl:call-template&gt;
				&lt;/assignedAuthor&gt;
			&lt;/author&gt;
		&lt;/xsl:for-each&gt;
		&lt;custodian xmlns=&quot;urn:hl7-org:v3&quot;&gt;
			&lt;assignedCustodian&gt;
				&lt;representedCustodianOrganization&gt;
					&lt;!-- fake NIC oid --&gt;
					&lt;id root=&quot;2.16.840.1.113883.3.26.1.6&quot;/&gt;
				&lt;/representedCustodianOrganization&gt;
			&lt;/assignedCustodian&gt;
		&lt;/custodian&gt;
	&lt;/xsl:template&gt;
	&lt;!-- =========================== --&gt;
	&lt;!--        body templates                          --&gt;
	&lt;!-- =========================== --&gt;
	&lt;!-- family history section template--&gt;
	&lt;xsl:template name=&quot;familyHistory_section&quot;&gt;
		&lt;xsl:param name=&quot;fh_sec&quot;/&gt;
		&lt;component xmlns=&quot;urn:hl7-org:v3&quot;&gt;
			&lt;section&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.3.88.11.83.125&quot;/&gt;
				&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.3.14&quot;/&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.10.20.1.4&quot;/&gt;
				&lt;code code=&quot;10157-6&quot; codeSystem=&quot;2.16.840.1.113883.6.1&quot; codeSystemName=&quot;LOINC&quot;/&gt;
				&lt;title&gt;Family history&lt;/title&gt;
				&lt;xsl:for-each select=&quot;\$fh_sec/trim:act/trim:relationship[@name='familyHistory']&quot;&gt;
					&lt;!-- call family history organizer template --&gt;
					&lt;xsl:call-template name=&quot;familyHistory_organizer&quot;&gt;
						&lt;xsl:with-param name=&quot;fh_org&quot; select=&quot;current()&quot;/&gt;
					&lt;/xsl:call-template&gt;
				&lt;/xsl:for-each&gt;
			&lt;/section&gt;
		&lt;/component&gt;
	&lt;/xsl:template&gt;
	&lt;!-- familyHistory organizer template --&gt;
	&lt;xsl:template name=&quot;familyHistory_organizer&quot;&gt;
		&lt;xsl:param name=&quot;fh_org&quot;/&gt;
		&lt;entry xmlns=&quot;urn:hl7-org:v3&quot;&gt;
			&lt;organizer classCode=&quot;CLUSTER&quot; moodCode=&quot;EVN&quot;&gt;
				&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.4.15&quot;/&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.10.20.1.23&quot;/&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.3.88.11.83.18&quot;/&gt;
				&lt;statusCode code=&quot;completed&quot;/&gt;
				&lt;xsl:for-each select=&quot;\$fh_org/trim:act/trim:relationship[@name= 'relative']&quot;&gt;
					&lt;xsl:if test=&quot;trim:act/trim:observation/trim:value/trim:ST&quot;&gt;
						&lt;subject&gt;
							&lt;relatedSubject classCode=&quot;PRS&quot;&gt;
								&lt;xsl:call-template name=&quot;valueSet_relatives&quot;&gt;
									&lt;xsl:with-param name=&quot;trim_dispNm&quot; select=&quot;trim:act/trim:observation/trim:value/trim:ST&quot;/&gt;
								&lt;/xsl:call-template&gt;
							&lt;/relatedSubject&gt;
						&lt;/subject&gt;
					&lt;/xsl:if&gt;
				&lt;/xsl:for-each&gt;
				&lt;xsl:for-each select=&quot;\$fh_org/trim:act/trim:relationship[@name= 'cancerType']&quot;&gt;
					&lt;xsl:if test=&quot;trim:act/trim:observation/trim:value/trim:CE&quot;&gt;
						&lt;!-- call family history observation cancerType template --&gt;
						&lt;xsl:call-template name=&quot;familyHistory_observation_cancerType&quot;&gt;
							&lt;xsl:with-param name=&quot;fh_obs&quot; select=&quot;current()&quot;/&gt;
							&lt;xsl:with-param name=&quot;fh_act&quot; select=&quot;\$fh_org/trim:act&quot;/&gt;
						&lt;/xsl:call-template&gt;
					&lt;/xsl:if&gt;
				&lt;/xsl:for-each&gt;
				&lt;xsl:for-each select=&quot;\$fh_org/trim:act/trim:relationship[@name= 'test']&quot;&gt;
					&lt;xsl:if test=&quot;trim:act/trim:observation/trim:value/trim:SETCE&quot;&gt;
						&lt;!-- call family history observation geneticMarker template --&gt;
						&lt;xsl:call-template name=&quot;familyHistory_observation_geneticMarker&quot;&gt;
							&lt;xsl:with-param name=&quot;fh_obs&quot; select=&quot;current()&quot;/&gt;
							&lt;xsl:with-param name=&quot;fh_act&quot; select=&quot;\$fh_org/trim:act&quot;/&gt;
						&lt;/xsl:call-template&gt;
					&lt;/xsl:if&gt;
				&lt;/xsl:for-each&gt;
			&lt;/organizer&gt;
		&lt;/entry&gt;
	&lt;/xsl:template&gt;
	&lt;!-- familyHistory observation templates--&gt;
	&lt;xsl:template name=&quot;familyHistory_observation_cancerType&quot;&gt;
		&lt;xsl:param name=&quot;fh_obs&quot;/&gt;
		&lt;xsl:param name=&quot;fh_act&quot;/&gt;
		&lt;component xmlns=&quot;urn:hl7-org:v3&quot;&gt;
			&lt;observation classCode=&quot;OBS&quot; moodCode=&quot;EVN&quot;&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.10.20.1.22&quot; assigningAuthorityName=&quot;CCD&quot;/&gt;
				&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.4.13&quot; assigningAuthorityName=&quot;IHE PCC&quot;/&gt;
				&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.4.13.3&quot; assigningAuthorityName=&quot;IHE PCC&quot;/&gt;
				&lt;id nullFlavor=&quot;NI&quot;/&gt;
				&lt;code code=&quot;404684003&quot; displayName=&quot;Finding&quot; codeSystemName=&quot;SNOMED CT&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot;/&gt;
				&lt;text&gt;
					&lt;reference/&gt;
				&lt;/text&gt;
				&lt;statusCode code=&quot;completed&quot;/&gt;
				&lt;xsl:if test=&quot;\$fh_obs/trim:act/trim:observation/trim:value/trim:CE/trim:displayName&quot;&gt;
					&lt;xsl:call-template name=&quot;valueSet_cancerTypes&quot;&gt;
						&lt;xsl:with-param name=&quot;trim_dispNm&quot; select=&quot;trim:act/trim:observation/trim:value/trim:CE/trim:displayName&quot;/&gt;
					&lt;/xsl:call-template&gt;
				&lt;/xsl:if&gt;
			&lt;/observation&gt;
		&lt;/component&gt;
	&lt;/xsl:template&gt;
	&lt;xsl:template name=&quot;familyHistory_observation_geneticMarker&quot;&gt;
		&lt;xsl:param name=&quot;fh_obs&quot;/&gt;
		&lt;xsl:param name=&quot;fh_act&quot;/&gt;
		&lt;component xmlns=&quot;urn:hl7-org:v3&quot;&gt;
			&lt;observation classCode=&quot;OBS&quot; moodCode=&quot;EVN&quot;&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.10.20.1.22&quot; assigningAuthorityName=&quot;CCD&quot;/&gt;
				&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.4.13&quot; assigningAuthorityName=&quot;IHE PCC&quot;/&gt;
				&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.4.13.3&quot; assigningAuthorityName=&quot;IHE PCC&quot;/&gt;
				&lt;id nullFlavor=&quot;NI&quot;/&gt;
				&lt;code code=&quot;ASSERTION&quot; codeSystem=&quot;2.16.840.1.113883.5.4&quot;/&gt;
				&lt;text&gt;
					&lt;reference/&gt;
				&lt;/text&gt;
				&lt;statusCode code=&quot;completed&quot;/&gt;
				&lt;xsl:if test=&quot; trim:act/trim:observation/trim:value/trim:SETCE/trim:displayName&quot;&gt;
					&lt;xsl:call-template name=&quot;valueSet_tests&quot;&gt;
						&lt;xsl:with-param name=&quot;trim_dispNm&quot; select=&quot;trim:act/trim:observation/trim:value/trim:SETCE/trim:displayName&quot;/&gt;
					&lt;/xsl:call-template&gt;
				&lt;/xsl:if&gt;
			&lt;/observation&gt;
		&lt;/component&gt;
	&lt;/xsl:template&gt;
	&lt;!-- vitalSign section template --&gt;
	&lt;xsl:template name=&quot;vitalSigns_section&quot;&gt;
		&lt;xsl:param name=&quot;vital_sec&quot;/&gt;
		&lt;component&gt;
			&lt;section&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.10.20.1.16&quot;/&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.3.88.11.83.119&quot;/&gt;
				&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.3.25&quot;/&gt;
				&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.1.5.3.2&quot;/&gt;
				&lt;code code=&quot;8716-3&quot; codeSystem=&quot;2.16.840.1.113883.6.1&quot; codeSystemName=&quot;LOINC&quot; displayName=&quot;vital signs&quot;/&gt;
				&lt;title&gt;Vital signs&lt;/title&gt;
				&lt;xsl:for-each select=&quot;\$vital_sec/trim:act/trim:observation&quot;&gt;
					&lt;xsl:call-template name=&quot;vitalSigns_organizer&quot;&gt;
						&lt;xsl:with-param name=&quot;vitalOrgniz&quot; select=&quot;current()&quot;/&gt;
						&lt;xsl:with-param name=&quot;vitalId&quot; select=&quot;\$vital_sec/trim:id/trim:II&quot;/&gt;
					&lt;/xsl:call-template&gt;
				&lt;/xsl:for-each&gt;
			&lt;/section&gt;
		&lt;/component&gt;
	&lt;/xsl:template&gt;
	&lt;!-- vitalSign organizer --&gt;
	&lt;xsl:template name=&quot;vitalSigns_organizer&quot;&gt;
		&lt;xsl:param name=&quot;vitalOrgniz&quot;/&gt;
		&lt;xsl:param name=&quot;vitalId&quot;/&gt;
		&lt;entry&gt;
			&lt;organizer classCode=&quot;CLUSTER&quot; moodCode=&quot;EVN&quot;&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.10.20.1.32&quot;/&gt;
				&lt;templateId root=&quot;2.16.840.1.113883.10.20.1.35&quot;/&gt;
				&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.4.13.1&quot;/&gt;
				&lt;xsl:call-template name=&quot;make_II&quot;&gt;
					&lt;xsl:with-param name=&quot;II_root&quot; select=&quot;\$vitalId/trim:root&quot;/&gt;
					&lt;xsl:with-param name=&quot;II_ext&quot; select=&quot;\$vitalId/trim:extension&quot;/&gt;
				&lt;/xsl:call-template&gt;
				&lt;code code=&quot;46680005&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; codeSystemName=&quot;SNOMED CT&quot; displayName=&quot;Vital signs&quot;/&gt;
				&lt;statusCode code=&quot;completed&quot;/&gt;
				&lt;effectiveTime nullFlavor=&quot;NI&quot;/&gt;
				&lt;xsl:for-each select=&quot;\$vitalOrgniz/trim:value&quot;&gt;
					&lt;xsl:call-template name=&quot;vitalSign_observation&quot;&gt;
						&lt;xsl:with-param name=&quot;vital_value&quot; select=&quot;current()&quot;/&gt;
					&lt;/xsl:call-template&gt;
				&lt;/xsl:for-each&gt;
			&lt;/organizer&gt;
		&lt;/entry&gt;
	&lt;/xsl:template&gt;
	&lt;!-- vitalSign observation --&gt;
	&lt;xsl:template name=&quot;vitalSign_observation&quot;&gt;
		&lt;xsl:param name=&quot;vital_value&quot;/&gt;
		&lt;xsl:if test=&quot;string-length(\$vital_value/trim:ST) and not(\$vital_value/trim:valueSet)&quot;&gt;
			&lt;component&gt;
				&lt;observation classCode=&quot;OBS&quot; moodCode=&quot;EVN&quot;&gt;
					&lt;templateId root=&quot;2.16.840.1.113883.10.20.1.31&quot;/&gt;
					&lt;templateId root=&quot;2.16.840.1.113883.3.88.11.83.14&quot;/&gt;
					&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.4.13&quot;/&gt;
					&lt;templateId root=&quot;1.3.6.1.4.1.19376.1.5.3.1.4.13.2&quot;/&gt;
					&lt;xsl:variable name=&quot;vital_label&quot; select=&quot;trim:label&quot;/&gt;
					&lt;code&gt;
						&lt;xsl:if test=&quot;(\$vital_label='T: ') or (\$vital_label = 'P: ') or (\$vital_label = 'Wt: ') or (\$vital_label = 'R: ') or (\$vital_label = 'BP: ') or (\$vital_label = 'Ht: ')&quot;&gt;
							&lt;xsl:choose&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'T: ')&quot;&gt;
									&lt;xsl:attribute name=&quot;code&quot;&gt;&lt;xsl:value-of select=&quot;8310-5&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;xsl:attribute name=&quot;displayName&quot;&gt;&lt;xsl:value-of select=&quot;'Body temperature'&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;originalText&gt;T:&lt;/originalText&gt;
								&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'P: ')&quot;&gt;
									&lt;xsl:attribute name=&quot;code&quot;&gt;&lt;xsl:value-of select=&quot;8867-4&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;xsl:attribute name=&quot;displayName&quot;&gt;&lt;xsl:value-of select=&quot;'Heart rate'&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;originalText&gt;P:&lt;/originalText&gt;
								&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'Wt: ')&quot;&gt;
									&lt;xsl:attribute name=&quot;code&quot;&gt;&lt;xsl:value-of select=&quot;8310-5&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;xsl:attribute name=&quot;displayName&quot;&gt;&lt;xsl:value-of select=&quot;'Body weight'&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;originalText&gt;Wt:&lt;/originalText&gt;
								&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'R: ')&quot;&gt;
									&lt;xsl:attribute name=&quot;code&quot;&gt;&lt;xsl:value-of select=&quot;9279-1&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;xsl:attribute name=&quot;displayName&quot;&gt;&lt;xsl:value-of select=&quot;'Respiration Rate'&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;originalText&gt;R:&lt;/originalText&gt;
								&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'BP: ')&quot;&gt;
									&lt;xsl:attribute name=&quot;code&quot;&gt;&lt;xsl:value-of select=&quot;8480-6&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;xsl:attribute name=&quot;displayName&quot;&gt;&lt;xsl:value-of select=&quot;'Systolic BP'&quot;/&gt;&lt;/xsl:attribute&gt;
								&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'Ht:: ')&quot;&gt;
									&lt;xsl:attribute name=&quot;code&quot;&gt;&lt;xsl:sequence select=&quot;'8302-2'&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;xsl:attribute name=&quot;displayName&quot;&gt;&lt;xsl:value-of select=&quot;'Body height'&quot;/&gt;&lt;/xsl:attribute&gt;
									&lt;originalText&gt;Ht:&lt;/originalText&gt;
								&lt;/xsl:when&gt;
							&lt;/xsl:choose&gt;
						&lt;/xsl:if&gt;
						&lt;xsl:if test=&quot;not(\$vital_label)&quot;&gt;
							&lt;xsl:attribute name=&quot;code&quot;&gt;&lt;xsl:value-of select=&quot;8462-4&quot;/&gt;&lt;/xsl:attribute&gt;
							&lt;xsl:attribute name=&quot;displayName&quot;&gt;&lt;xsl:value-of select=&quot;'Diastolic BP'&quot;/&gt;&lt;/xsl:attribute&gt;
						&lt;/xsl:if&gt;
						&lt;xsl:attribute name=&quot;codeSystem&quot;&gt;&lt;xsl:value-of select=&quot;'2.16.840.1.113883.6.1'&quot;/&gt;&lt;/xsl:attribute&gt;
						&lt;xsl:attribute name=&quot;codeSystemName&quot;&gt;&lt;xsl:value-of select=&quot;'LOINC'&quot;/&gt;&lt;/xsl:attribute&gt;
					&lt;/code&gt;
					&lt;statusCode code=&quot;completed&quot;/&gt;
					&lt;effectiveTime nullFlavor=&quot;NI&quot;/&gt;
					&lt;value&gt;
						&lt;xsl:attribute name=&quot;xsi:type&quot; namespace=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;xsl:value-of select=&quot;'PQ'&quot;/&gt;&lt;/xsl:attribute&gt;
						&lt;xsl:attribute name=&quot;value&quot;&gt;&lt;xsl:value-of select=&quot;\$vital_value/trim:ST&quot;/&gt;&lt;/xsl:attribute&gt;
						&lt;xsl:attribute name=&quot;unit&quot;&gt;
							&lt;xsl:choose&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'T: ')&quot;&gt;&lt;xsl:value-of select=&quot;'Cel'&quot;/&gt;&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'P: ')&quot;&gt;&lt;xsl:value-of select=&quot;'min'&quot;/&gt;&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'R: ')&quot;&gt;&lt;xsl:value-of select=&quot;'min'&quot;/&gt;&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'Wt: ')&quot;&gt;&lt;xsl:value-of select=&quot;'kg'&quot;/&gt;&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'Ht: ')&quot;&gt;&lt;xsl:value-of select=&quot;'cm'&quot;/&gt;&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;(\$vital_label = 'BP: ')&quot;&gt;&lt;xsl:value-of select=&quot;'mm[Hg]'&quot;/&gt;&lt;/xsl:when&gt;
								&lt;xsl:when test=&quot;not(\$vital_label) and (string-length(\$vital_value/trim:ST)&gt;0)&quot;&gt;&lt;xsl:value-of select=&quot;'mm[Hg]'&quot;/&gt;&lt;/xsl:when&gt;
							&lt;/xsl:choose&gt;&lt;/xsl:attribute&gt;
					&lt;/value&gt;
				&lt;/observation&gt;
			&lt;/component&gt;
		&lt;/xsl:if&gt;
	&lt;/xsl:template&gt;
	&lt;!-- ============================ --&gt;
	&lt;!-- valueSet mapping templates                  --&gt;
	&lt;!-- ============================ --&gt;
	&lt;xsl:template name=&quot;valueSet_relatives&quot;&gt;
		&lt;!--  baseline note, valueSet: relatives
            Mother
			Father
         --&gt;
		&lt;xsl:param name=&quot;trim_dispNm&quot;/&gt;
		&lt;xsl:choose&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Mother'&quot;&gt;
				&lt;code xmlns=&quot;urn:hl7-org:v3&quot; code=&quot;MTH&quot; codeSystem=&quot;2.16.840.1.113883.5.111&quot; codeSystemName=&quot;HL7 FamilyMember&quot; displayName=&quot;mother&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/code&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Father'&quot;&gt;
				&lt;code xmlns=&quot;urn:hl7-org:v3&quot; code=&quot;FTH&quot; codeSystem=&quot;2.16.840.1.113883.5.111&quot; codeSystemName=&quot;HL7 FamilyMember&quot; displayName=&quot;father&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/code&gt;
			&lt;/xsl:when&gt;
		&lt;/xsl:choose&gt;
	&lt;/xsl:template&gt;
	&lt;xsl:template name=&quot;valueSet_tests&quot;&gt;
		&lt;!--  baseline note, valueSet: tests
            BRCA 1 positive
			BRCA 2 positive
			Unknown
         --&gt;
		&lt;xsl:param name=&quot;trim_dispNm&quot;/&gt;
		&lt;xsl:choose&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='BRCA 1 positive'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;BRCA 1 positive&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='BRCA 2 positive'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;BRCA 2 positive&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Unknown'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; nullFlavor=&quot;UNK&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
		&lt;/xsl:choose&gt;
	&lt;/xsl:template&gt;
	&lt;xsl:template name=&quot;valueSet_cancerTypes&quot;&gt;
		&lt;!-- baseline note, valueSet: cancerTypes 
				Breast Cancer
				Bone
				Brain, spinal cord (central nervous system)
                Cervical carcinoma, invasive
				Cervical carcinoma, in situ
				Colon/rectal
				Hodgkin's disease
				Intestinal
				Kidney
				Leukemia or abnormal bone marrow cells that may lead to leukemia (myelodysplasia)
				Lung
				Lymphoma
				Ovarian
				Pancreatic
				Prostate
				Skin: basal or squamous cell
				Skin: melanoma
				Other cancer:
		--&gt;
		&lt;xsl:param name=&quot;trim_dispNm&quot;/&gt;
		&lt;xsl:choose&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Breast Cancer'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Breast Cancer&quot;/&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Bone'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Bone&quot;/&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Brain, spinal cord (central nervous system)'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Brain, spinal cord (central nervous system)&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Cervical carcinoma, invasive'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Cervical carcinoma, invasive&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Cervical carcinoma, in situ'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Cervical carcinoma, in situ&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Colon/rectal'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Colon/rectal&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;starts-with(\$trim_dispNm, 'Hodgkin')&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Hodgkin&amp;quot;s disease&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Intestinal'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Intestinal&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Kidney'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Kidney&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Leukemia or abnormal bone marrow cells that may lead to leukemia (myelodysplasia)'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Leukemia or abnormal bone marrow cells that may lead to leukemia (myelodysplasia)&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Lung'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Lung&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Lymphoma'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Lymphoma&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Ovarian'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Ovarian&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Pancreatic'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Pancreatic&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Prostate'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Prostate&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Skin: basal or squamous cell'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Skin: basal or squamous cell&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='Skin: melanoma'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;Skin: melanoma&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
		&lt;/xsl:choose&gt;
	&lt;/xsl:template&gt;
	&lt;xsl:template name=&quot;valueSet_breastCancerType&quot;&gt;
		&lt;!--  baseline note, valueSet: breastCancerType
			DCIS
			LCIS
			invasive
        --&gt;
		&lt;xsl:param name=&quot;trim_dispNm&quot;/&gt;
		&lt;xsl:choose&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='DCIS'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;DCIS&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='LCIS'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;LCIS&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:when test=&quot;\$trim_dispNm='invasive'&quot;&gt;
				&lt;value xmlns=&quot;urn:hl7-org:v3&quot; xsi:type=&quot;CD&quot; code=&quot;xxx-xxx&quot; codeSystem=&quot;2.16.840.1.113883.6.96&quot; displayName=&quot;invasive&quot;&gt;
					&lt;originalText&gt;
						&lt;xsl:value-of select=&quot;\$trim_dispNm&quot;/&gt;
					&lt;/originalText&gt;
				&lt;/value&gt;
			&lt;/xsl:when&gt;
		&lt;/xsl:choose&gt;
	&lt;/xsl:template&gt;
	&lt;!-- ============================ --&gt;
	&lt;!-- general utility templates                      --&gt;
	&lt;!-- ============================ --&gt;
	&lt;xsl:template name=&quot;make_II&quot;&gt;
		&lt;xsl:param name=&quot;II_root&quot;/&gt;
		&lt;xsl:param name=&quot;II_ext&quot;/&gt;
		&lt;xsl:param name=&quot;II_assAuth&quot;/&gt;
		&lt;xsl:choose&gt;
			&lt;xsl:when test=&quot;string-length(\$II_root)&gt;0&quot;&gt;
				&lt;id xmlns=&quot;urn:hl7-org:v3&quot;&gt;
					&lt;xsl:attribute name=&quot;root&quot;&gt;&lt;xsl:value-of select=&quot;\$II_root&quot;/&gt;&lt;/xsl:attribute&gt;
					&lt;xsl:if test=&quot;string-length(\$II_ext)&gt;0&quot;&gt;
						&lt;xsl:attribute name=&quot;extension&quot;&gt;&lt;xsl:value-of select=&quot;\$II_ext&quot;/&gt;&lt;/xsl:attribute&gt;
					&lt;/xsl:if&gt;
					&lt;xsl:if test=&quot;string-length(\$II_assAuth)&gt;0&quot;&gt;
						&lt;xsl:attribute name=&quot;assigningAuthorityName&quot;&gt;&lt;xsl:value-of select=&quot;\$II_assAuth&quot;/&gt;&lt;/xsl:attribute&gt;
					&lt;/xsl:if&gt;
				&lt;/id&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:otherwise&gt;
				&lt;id xmlns=&quot;urn:hl7-org:v3&quot; nullFlavor=&quot;NI&quot;/&gt;
			&lt;/xsl:otherwise&gt;
		&lt;/xsl:choose&gt;
	&lt;/xsl:template&gt;
	&lt;xsl:template name=&quot;make_code_CD&quot;&gt;
		&lt;xsl:param name=&quot;CD_code&quot;/&gt;
		&lt;xsl:param name=&quot;CD_dispNm&quot;/&gt;
		&lt;xsl:param name=&quot;CD_codeSys&quot;/&gt;
		&lt;xsl:param name=&quot;CD_codeSysNm&quot;/&gt;
		&lt;xsl:choose&gt;
			&lt;xsl:when test=&quot;string-length(\$CD_code)&gt;0&quot;&gt;
				&lt;code xmlns=&quot;urn:hl7-org:v3&quot;&gt;
					&lt;xsl:attribute name=&quot;code&quot;&gt;&lt;xsl:value-of select=&quot;\$CD_code&quot;/&gt;&lt;/xsl:attribute&gt;
					&lt;xsl:if test=&quot;string-length(\$CD_dispNm)&gt;0&quot;&gt;
						&lt;xsl:attribute name=&quot;displayName&quot;&gt;&lt;xsl:value-of select=&quot;\$CD_dispNm&quot;/&gt;&lt;/xsl:attribute&gt;
					&lt;/xsl:if&gt;
					&lt;xsl:if test=&quot;string-length(\$CD_codeSys)&gt;0&quot;&gt;
						&lt;xsl:attribute name=&quot;codeSystem&quot;&gt;&lt;xsl:value-of select=&quot;\$CD_codeSys&quot;/&gt;&lt;/xsl:attribute&gt;
					&lt;/xsl:if&gt;
					&lt;xsl:if test=&quot;string-length(\$CD_codeSysNm)&gt;0&quot;&gt;
						&lt;xsl:attribute name=&quot;codeSystemName&quot;&gt;&lt;xsl:value-of select=&quot;\$CD_codeSysNm&quot;/&gt;&lt;/xsl:attribute&gt;
					&lt;/xsl:if&gt;
				&lt;/code&gt;
			&lt;/xsl:when&gt;
			&lt;xsl:otherwise&gt;
				&lt;code xmlns=&quot;urn:hl7-org:v3&quot; nullFlavor=&quot;NI&quot;/&gt;
			&lt;/xsl:otherwise&gt;
		&lt;/xsl:choose&gt;
	&lt;/xsl:template&gt;
	&lt;xsl:template name=&quot;make_name&quot;&gt;
		&lt;xsl:param name=&quot;trimNm&quot;/&gt;
		&lt;name xmlns=&quot;urn:hl7-org:v3&quot;&gt;
			&lt;xsl:if test=&quot;string-length(\$trimNm/trim:EN/trim:use)&quot;&gt;
				&lt;xsl:attribute name=&quot;use&quot;&gt;&lt;xsl:value-of select=&quot;\$trimNm/trim:EN/trim:use&quot;/&gt;&lt;/xsl:attribute&gt;
			&lt;/xsl:if&gt;
			&lt;xsl:for-each select=&quot;\$trimNm/trim:EN/trim:part&quot;&gt;
				&lt;xsl:if test=&quot;trim:type='FAM'&quot;&gt;
					&lt;family&gt;
						&lt;xsl:value-of select=&quot;trim:ST&quot;/&gt;
					&lt;/family&gt;
				&lt;/xsl:if&gt;
				&lt;xsl:if test=&quot;trim:type='GIV'&quot;&gt;
					&lt;given&gt;
						&lt;xsl:value-of select=&quot;trim:ST&quot;/&gt;
					&lt;/given&gt;
				&lt;/xsl:if&gt;
			&lt;/xsl:for-each&gt;
		&lt;/name&gt;
	&lt;/xsl:template&gt;
&lt;/xsl:stylesheet&gt;