&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;!--
This file was generated by Altova MapForce 2011r3

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
--&gt;
&lt;xsl:stylesheet version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fn=&quot;http://www.w3.org/2005/xpath-functions&quot; xmlns:ns0=&quot;urn:tolven-org:trim:4.0&quot; exclude-result-prefixes=&quot;xs fn ns0&quot;&gt;
	&lt;xsl:output method=&quot;xml&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot;/&gt;
	&lt;xsl:template match=&quot;/&quot;&gt;
		&lt;ClinicalDocument xmlns=&quot;urn:hl7-org:v3&quot;&gt;
			&lt;xsl:attribute name=&quot;xsi:schemaLocation&quot; namespace=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; select=&quot;'urn:hl7-org:v3 D:/workspace/Transcend_Trim_Mapping/mapping/CDA_XSD/cda/CDA.xsd'&quot;/&gt;
			&lt;xsl:for-each select=&quot;ns0:trim&quot;&gt;
				&lt;xsl:variable name=&quot;var1_act&quot; as=&quot;node()?&quot; select=&quot;ns0:act&quot;/&gt;
				&lt;xsl:variable name=&quot;var2_resultof_create_attribute&quot; as=&quot;node()&quot;&gt;
					&lt;xsl:attribute name=&quot;codeSystem&quot; namespace=&quot;&quot;&gt;
						&lt;xsl:value-of select=&quot;'2.16.840.1.113883.6.1'&quot;/&gt;
					&lt;/xsl:attribute&gt;
				&lt;/xsl:variable&gt;
				&lt;xsl:variable name=&quot;var3_resultof_create_attribute&quot; as=&quot;node()&quot;&gt;
					&lt;xsl:attribute name=&quot;codeSystemName&quot; namespace=&quot;&quot;&gt;
						&lt;xsl:value-of select=&quot;'LOINC'&quot;/&gt;
					&lt;/xsl:attribute&gt;
				&lt;/xsl:variable&gt;
				&lt;realmCode&gt;
					&lt;xsl:attribute name=&quot;code&quot; namespace=&quot;&quot;&gt;
						&lt;xsl:value-of select=&quot;'US'&quot;/&gt;
					&lt;/xsl:attribute&gt;
				&lt;/realmCode&gt;
				&lt;typeId&gt;
					&lt;xsl:attribute name=&quot;root&quot; namespace=&quot;&quot;&gt;
						&lt;xsl:value-of select=&quot;'2.16.840.1.113883.1.3'&quot;/&gt;
					&lt;/xsl:attribute&gt;
					&lt;xsl:attribute name=&quot;extension&quot; namespace=&quot;&quot; &gt;
						&lt;xsl:value-of select=&quot;'POCD_HD000040'&quot;/&gt;
					&lt;/xsl:attribute&gt;
				&lt;/typeId&gt;
				&lt;templateId&gt;
					&lt;xsl:attribute name=&quot;root&quot; namespace=&quot;&quot; &gt;
						&lt;xsl:value-of select=&quot;'2.16.840.1.113883.10.20.1'&quot;/&gt;
					&lt;/xsl:attribute&gt;
				&lt;/templateId&gt;
				&lt;templateId&gt;
					&lt;xsl:attribute name=&quot;root&quot; namespace=&quot;&quot; &gt;
						&lt;xsl:value-of select=&quot;'2.16.840.1.113883.3.88.11.32.1'&quot;/&gt;
					&lt;/xsl:attribute&gt;
				&lt;/templateId&gt;
				&lt;templateId&gt;
					&lt;xsl:attribute name=&quot;root&quot; namespace=&quot;&quot; &gt;
						&lt;xsl:value-of select=&quot;'1.3.6.1.4.1.19376.1.5.3.1.1.1'&quot;/&gt;
					&lt;/xsl:attribute&gt;
				&lt;/templateId&gt;
				&lt;templateId&gt;
					&lt;xsl:attribute name=&quot;root&quot; namespace=&quot;&quot; &gt;
						&lt;xsl:value-of select=&quot;'2.16.840.1.113883.10.20.3'&quot;/&gt;
					&lt;/xsl:attribute&gt;
				&lt;/templateId&gt;
			&lt;/xsl:for-each&gt;
		&lt;/ClinicalDocument&gt;
	&lt;/xsl:template&gt;
&lt;/xsl:stylesheet&gt;