
/*
 * 
 */

package com.mirth.connect.connectors.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed May 25 09:01:07 EDT 2011
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "DefaultAcceptMessageService", 
                  wsdlLocation = "http://localhost:9081/services/Mirth?wsdl",
                  targetNamespace = "http://ws.connectors.connect.mirth.com/") 
public class DefaultAcceptMessageService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.connectors.connect.mirth.com/", "DefaultAcceptMessageService");
    public final static QName DefaultAcceptMessagePort = new QName("http://ws.connectors.connect.mirth.com/", "DefaultAcceptMessagePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9081/services/Mirth?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9081/services/Mirth?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public DefaultAcceptMessageService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DefaultAcceptMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DefaultAcceptMessageService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns DefaultAcceptMessage
     */
    @WebEndpoint(name = "DefaultAcceptMessagePort")
    public DefaultAcceptMessage getDefaultAcceptMessagePort() {
        return super.getPort(DefaultAcceptMessagePort, DefaultAcceptMessage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DefaultAcceptMessage
     */
    @WebEndpoint(name = "DefaultAcceptMessagePort")
    public DefaultAcceptMessage getDefaultAcceptMessagePort(WebServiceFeature... features) {
        return super.getPort(DefaultAcceptMessagePort, DefaultAcceptMessage.class, features);
    }

}
