package gov.nih.nci.cacis.datawarehouse.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.4
 */
public interface ClinicalDataWarehouseConstantsBase {
	public static final String SERVICE_NS = "http://datawarehouse.cacis.nci.nih.gov/ClinicalDataWarehouse";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "ClinicalDataWarehouseKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "ClinicalDataWarehouseResourceProperties");
	
}
